
package libraryWS;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibraryRemoteWS", targetNamespace = "http://domain/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryRemoteWS {

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEMedia", targetNamespace = "http://domain/", className = "libraryWS.GetEMedia")
    @ResponseWrapper(localName = "getEMediaResponse", targetNamespace = "http://domain/", className = "libraryWS.GetEMediaResponse")
    @Action(input = "http://domain/LibraryRemoteWS/getEMediaRequest", output = "http://domain/LibraryRemoteWS/getEMediaResponse")
    public String getEMedia();

}
