
package shelvesWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShelvesRemoteWSService", targetNamespace = "http://domain/", wsdlLocation = "http://nunos-mac-mini.local:8080/ShelvesRemoteWSService/ShelvesRemoteWS?WSDL")
public class ShelvesRemoteWSService
    extends Service
{

    private final static URL SHELVESREMOTEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHELVESREMOTEWSSERVICE_EXCEPTION;
    private final static QName SHELVESREMOTEWSSERVICE_QNAME = new QName("http://domain/", "ShelvesRemoteWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://nunos-mac-mini.local:8080/ShelvesRemoteWSService/ShelvesRemoteWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHELVESREMOTEWSSERVICE_WSDL_LOCATION = url;
        SHELVESREMOTEWSSERVICE_EXCEPTION = e;
    }

    public ShelvesRemoteWSService() {
        super(__getWsdlLocation(), SHELVESREMOTEWSSERVICE_QNAME);
    }

    public ShelvesRemoteWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHELVESREMOTEWSSERVICE_QNAME, features);
    }

    public ShelvesRemoteWSService(URL wsdlLocation) {
        super(wsdlLocation, SHELVESREMOTEWSSERVICE_QNAME);
    }

    public ShelvesRemoteWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHELVESREMOTEWSSERVICE_QNAME, features);
    }

    public ShelvesRemoteWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShelvesRemoteWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShelvesRemoteWS
     */
    @WebEndpoint(name = "ShelvesRemoteWSPort")
    public ShelvesRemoteWS getShelvesRemoteWSPort() {
        return super.getPort(new QName("http://domain/", "ShelvesRemoteWSPort"), ShelvesRemoteWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShelvesRemoteWS
     */
    @WebEndpoint(name = "ShelvesRemoteWSPort")
    public ShelvesRemoteWS getShelvesRemoteWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://domain/", "ShelvesRemoteWSPort"), ShelvesRemoteWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHELVESREMOTEWSSERVICE_EXCEPTION!= null) {
            throw SHELVESREMOTEWSSERVICE_EXCEPTION;
        }
        return SHELVESREMOTEWSSERVICE_WSDL_LOCATION;
    }

}
